CREATE TABLE accounts (
id INT AUTO_INCREMENT PRIMARY KEY,
naam VARCHAR(100),
email VARCHAR(100),
rol VARCHAR(50)
);

CREATE TABLE leden (
id INT AUTO_INCREMENT PRIMARY KEY,
naam VARCHAR(100),
email VARCHAR(100),
telefoon VARCHAR(20)
);

CREATE TABLE medewerkers (
id INT AUTO_INCREMENT PRIMARY KEY,
naam VARCHAR(100),
functie VARCHAR(100),
email VARCHAR(100)
);